### ISSUE TITLE
issues with verifying sketch

### ISSUE THREAD

**Issue by Fredlepp** [MauriceRowe/Sim-Racing-Pedals-with-Load-Cell#2]
i don't know what's append. i don't change anything

Arduino : 1.8.13 (Windows 10), Carte : "Arduino Micro"
C:\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Arduino\hardware -hardware C:\Users\fredl\AppData\Local\Arduino15\packages -tools C:\Arduino\tools-builder -tools C:\Arduino\hardware\tools\avr -tools C:\Users\fredl\AppData\Local\Arduino15\packages -built-in-libraries C:\Arduino\libraries -libraries C:\Users\fredl\OneDrive\Arduino\libraries -fqbn=arduino:avr:micro -vid-pid=2341_8037 -ide-version=10813 -build-path C:\USERS\FREDL\APPDATA\LOCAL\TEMP\arduino_build_806493 -warnings=none -build-cache C:\USERS\FREDL\APPDATA\LOCAL\TEMP\arduino_cache_516771 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avrdude.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.arduinoOTA.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -verbose C:\Users\fredl\OneDrive\Arduino\sketch_loadcell\sketch_loadcell.ino

C:\Arduino\arduino-builder -compile -logger=machine -hardware C:\Arduino\hardware -hardware C:\Users\fredl\AppData\Local\Arduino15\packages -tools C:\Arduino\tools-builder -tools C:\Arduino\hardware\tools\avr -tools C:\Users\fredl\AppData\Local\Arduino15\packages -built-in-libraries C:\Arduino\libraries -libraries C:\Users\fredl\OneDrive\Arduino\libraries -fqbn=arduino:avr:micro -vid-pid=2341_8037 -ide-version=10813 -build-path C:\USERS\FREDL\APPDATA\LOCAL\TEMP\arduino_build_806493 -warnings=none -build-cache C:\USERS\FREDL\APPDATA\LOCAL\TEMP\arduino_cache_516771 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avrdude.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.arduinoOTA.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -verbose C:\Users\fredl\OneDrive\Arduino\sketch_loadcell\sketch_loadcell.ino

Using board 'micro' from platform in folder: C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.3

Using core 'arduino' from platform in folder: C:\Users\fredl\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.3

Detecting libraries used...

"C:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_MICRO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8037 "-DUSB_MANUFACTURER=\"Unknown\"" "-DUSB_PRODUCT=\"Arduino Micro\"" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\micro" "C:\\USERS\\FREDL\\APPDATA\\LOCAL\\TEMP\\arduino_build_806493\\sketch\\sketch_loadcell.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for HX711.h: [HX711_Arduino_Library@0.7.4]

ResolveLibrary(HX711.h)

  -> candidates: [HX711_Arduino_Library@0.7.4]

"C:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_MICRO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8037 "-DUSB_MANUFACTURER=\"Unknown\"" "-DUSB_PRODUCT=\"Arduino Micro\"" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\micro" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\HX711_Arduino_Library\\src" "C:\\USERS\\FREDL\\APPDATA\\LOCAL\\TEMP\\arduino_build_806493\\sketch\\sketch_loadcell.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for Joystick.h: [ArduinoJoystickLibrary-master@2.0.7]

ResolveLibrary(Joystick.h)

  -> candidates: [ArduinoJoystickLibrary-master@2.0.7]

"C:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_MICRO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8037 "-DUSB_MANUFACTURER=\"Unknown\"" "-DUSB_PRODUCT=\"Arduino Micro\"" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\micro" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\HX711_Arduino_Library\\src" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\ArduinoJoystickLibrary-master\\src" "C:\\USERS\\FREDL\\APPDATA\\LOCAL\\TEMP\\arduino_build_806493\\sketch\\sketch_loadcell.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_MICRO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8037 "-DUSB_MANUFACTURER=\"Unknown\"" "-DUSB_PRODUCT=\"Arduino Micro\"" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\micro" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\HX711_Arduino_Library\\src" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\ArduinoJoystickLibrary-master\\src" "C:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\HX711_Arduino_Library\\src\\HX711.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_MICRO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8037 "-DUSB_MANUFACTURER=\"Unknown\"" "-DUSB_PRODUCT=\"Arduino Micro\"" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\micro" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\HX711_Arduino_Library\\src" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\ArduinoJoystickLibrary-master\\src" "C:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\ArduinoJoystickLibrary-master\\src\\DynamicHID\\DynamicHID.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_MICRO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8037 "-DUSB_MANUFACTURER=\"Unknown\"" "-DUSB_PRODUCT=\"Arduino Micro\"" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\micro" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\HX711_Arduino_Library\\src" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\ArduinoJoystickLibrary-master\\src" "C:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\ArduinoJoystickLibrary-master\\src\\Joystick.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Generating function prototypes...

"C:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_MICRO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8037 "-DUSB_MANUFACTURER=\"Unknown\"" "-DUSB_PRODUCT=\"Arduino Micro\"" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\micro" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\HX711_Arduino_Library\\src" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\ArduinoJoystickLibrary-master\\src" "C:\\USERS\\FREDL\\APPDATA\\LOCAL\\TEMP\\arduino_build_806493\\sketch\\sketch_loadcell.ino.cpp" -o "C:\\USERS\\FREDL\\APPDATA\\LOCAL\\TEMP\\arduino_build_806493\\preproc\\ctags_target_for_gcc_minus_e.cpp" -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Arduino\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\USERS\\FREDL\\APPDATA\\LOCAL\\TEMP\\arduino_build_806493\\preproc\\ctags_target_for_gcc_minus_e.cpp"

Compilation du croquis...

"C:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_MICRO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8037 "-DUSB_MANUFACTURER=\"Unknown\"" "-DUSB_PRODUCT=\"Arduino Micro\"" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\fredl\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\micro" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\HX711_Arduino_Library\\src" "-IC:\\Users\\fredl\\OneDrive\\Arduino\\libraries\\ArduinoJoystickLibrary-master\\src" "C:\\USERS\\FREDL\\APPDATA\\LOCAL\\TEMP\\arduino_build_806493\\sketch\\sketch_loadcell.ino.cpp" -o "C:\\USERS\\FREDL\\APPDATA\\LOCAL\\TEMP\\arduino_build_806493\\sketch\\sketch_loadcell.ino.cpp.o"

sketch_loadcell:4:18: error: no matching function for call to 'HX711::HX711(int, int)'

   HX711 scale(0,1);

                  ^

In file included from C:\Users\fredl\OneDrive\Arduino\sketch_loadcell\sketch_loadcell.ino:1:0:

C:\Users\fredl\OneDrive\Arduino\libraries\HX711_Arduino_Library\src/HX711.h:30:3: note: candidate: HX711::HX711()

   HX711();

   ^~~~~

C:\Users\fredl\OneDrive\Arduino\libraries\HX711_Arduino_Library\src/HX711.h:30:3: note:   candidate expects 0 arguments, 2 provided

C:\Users\fredl\OneDrive\Arduino\libraries\HX711_Arduino_Library\src/HX711.h:19:7: note: candidate: constexpr HX711::HX711(const HX711&)

 class HX711

       ^~~~~

C:\Users\fredl\OneDrive\Arduino\libraries\HX711_Arduino_Library\src/HX711.h:19:7: note:   candidate expects 1 argument, 2 provided

Utilisation de la bibliothèque HX711_Arduino_Library version 0.7.4 dans le dossier: C:\Users\fredl\OneDrive\Arduino\libraries\HX711_Arduino_Library 

Utilisation de la bibliothèque ArduinoJoystickLibrary-master version 2.0.7 dans le dossier: C:\Users\fredl\OneDrive\Arduino\libraries\ArduinoJoystickLibrary-master 

exit status 1

no matching function for call to 'HX711::HX711(int, int)'

**Comment by Fredlepp** [comment]
If I delete "(0,1)" after "hx711 scale" the skectch it's done but it doesn't works

**Comment by fastrella** [comment]
I have the same problem

**Comment by fastrella** [comment]
If I delete "(0,1)" after "hx711 scale" the skectch it's done but it doesn't works

**Comment by Fredlepp** [comment]
i found an other solution.

take that, include 2 butons and handbrake,i pick few sketch an get a mix, this is probably not perfect, but it works:

#include <Joystick.h>

#include <HX711.h>

// HX711 circuit wiring
const int LOADCELL_DOUT_PIN = A2;
const int LOADCELL_SCK_PIN = A3;

HX711 scale;

Joystick_ Joystick;

void setup() {
  Serial.begin(128000);
  // Button Pins set to input with pull up risistors
  pinMode(9, INPUT_PULLUP);
  pinMode(10, INPUT_PULLUP);
  pinMode(11, INPUT_PULLUP);
  pinMode(12, INPUT_PULLUP);
  // set potentiometer pins to input
  pinMode(A0, INPUT);
 scale.set_scale(-30000); 
scale.begin(LOADCELL_DOUT_PIN, LOADCELL_SCK_PIN);
  
  // Initialize Joystick Library
  Joystick.begin();
}

// Constant that maps the phyical pin to the joystick button.
const int pinToButtonMap = 9;
//const int pinToButtonMap = A0;

// Last state of the button
int lastButtonState[5] = {0,0,0,0,0};

void loop() {

  {int pot = analogRead(A0);
int mapped = map(pot,0,1023,0,255);
{Joystick.setThrottle(mapped);}}

Joystick.setZAxis(abs(scale.get_units(1)));     // read load cell set z axis

  // Read pin values
  for (int index = 0; index < 4; index++)
  {
    int currentButtonState = !digitalRead(index + pinToButtonMap);
    if (currentButtonState != lastButtonState[index])
    {
      Joystick.setButton(index, currentButtonState);
      lastButtonState[index] = currentButtonState;
    }
  }

  delay(10);
}

but HX711, is very slow and get latency in game, search on gogle about this  problem, you have to unsolder the 15th pin of the chip and solder it on  VCC to increase fequency to 80 FPS and the game will be better

**Comment by Fredlepp** [comment]
probably, you have to change the line sacle.set_scale(**_-3000_**) to adapt the range of pedale axis on windows . i use a little 20Kg loadcell from china
